### ISSUE TITLE
is it possible to write to jpg at all? 

### ISSUE THREAD

**Issue by ELI7VH** [photoshell/rawkit#127]
I searched the docs and can't seem to find anything that indicates you can write to jpg.

**Comment by SamWhited** [comment]
The output formats for raw files are currently ppm and tiff as documented [here](http://rawkit.readthedocs.io/en/latest/api/rawkit.html#rawkit.raw.output_file_types).

To write a JPEG you will need to use another library that supports JPEG compression, such as [Wand](http://docs.wand-py.org/en/0.4.4/). It's been a while since I've done this and I remember Wand having trouble with RGB tuples, so it might be better to buffer a PPM or TIFF in memory and then use Wand to convert that. You can use Wand to [read an input stream](http://docs.wand-py.org/en/0.4.4/) or [read a blob](http://docs.wand-py.org/en/0.4.4/guide/read.html#read-a-blob) to do this relatively quickly.

**Comment by campaul** [comment]
Here's an example that uses `pillow` to save the RGB buffer to a JPEG.

```python
from rawkit.raw import Raw
from PIL import Image


with Raw(filename='/path/to/file') as raw:
    rgb_buffer = raw.to_buffer()

    # Convert the buffer from [r, g, b, r...] to [(r, g, b), (r, g, b)...]
    rgb_tuples = [
        tuple(rgb_buffer[i:i+3]) for i in range(0, len(rgb_buffer), 3)
    ]

    image = Image.new('RGB', [raw.metadata.width, raw.metadata.height])
    image.putdata(rgb_tuples)
    image.save('foo.jpg')
```

**Comment by campaul** [comment]
I added an `examples` directory with this example.
