### ISSUE TITLE
Instantiating Raw with non-ascii characters not working

### ISSUE THREAD

**Issue by Unkraut3** [photoshell/rawkit#152]
When I try to instantiate Raw with a filename containing German accents such as ü I get the following error:
`UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 39: ordinal not in range(128)`

The reason seems obvious, as the filename is passed to libraw as ascii:
`self.libraw.libraw_open_file(self.data, filename.encode('ascii'))`

Maybe using utf8 or the like instead of ascii would be good.

**Comment by Unkraut3** [comment]
In rawkit.raw, class Raw, function  \_\_init\_\_, replacing
`self.libraw.libraw_open_file(self.data, filename.encode('ascii'))`
with
`self.libraw.libraw_open_file(self.data, filename.encode('utf-8'))`
solves the issue for me. At least on Linux. Not sure about Windows.

**Comment by SamWhited** [comment]
I was thinking that libraw only accepted ASCII for some reason, but I can't find any documentation to confirm that now and it appears to just take a byte array, so if that worked for you I'll go ahead and fix it. We don't want to just encode as utf-8 because I think @campaul wants to support Windows and IIRC it uses UTF-16 (*sigh*) but maybe we can just pass the bytes through and let the user deal with that. Or does Python have a concept of an "OS String"? I'll see what I can find out. I really hate how this language handles strings and encodings.
